### ISSUE TITLE
Can't see or change iZone temperature

### ISSUE THREAD

**Issue by LeVuHoang** [Swamp-Ig/pizone#8] opened 2021-05-15 02:36 UTC
Hi all,
The iZone component worked perfectly until recently, I can turn on and turn off iZone but can't change the temperature.
When I changed the gauge and refresh homeassistant, it went back to 0.
![iZone](https://user-images.githubusercontent.com/8195564/118345757-30cf0800-b569-11eb-995c-81bdbca8ed51.png)

I have latest HomeAssistant version, my iZone device details as below
```
hvac_modes:
  - 'off'
  - cool
  - heat
  - heat_cool
  - fan_only
  - dry
min_temp: 15
max_temp: 30
target_temp_step: 0.5
fan_modes:
  - low
  - medium
  - high
preset_modes:
  - none
  - eco
current_temperature: null
fan_mode: low
preset_mode: none
supply_temperature: null
temp_setpoint: 26
control_zone: 15
control_zone_name: null
control_zone_setpoint: null
friendly_name: iZone Controller 0000426xx
supported_features: 24
```
Discovery
`2021-05-15 10:31:23 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'ASPort_12107,Mac_0000426xx,IP_192.168.1.x,iZoneV2,iLight,iDrate,iPower'`
Polling
```
2021-05-15 10:34:44 DEBUG (MainThread) [pizone.controller] Polling unit 0000426xx.
2021-05-15 10:31:36 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2021-05-15 10:31:36 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2021-05-15 10:31:37 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
```
I can see it writes message when I turned on and off but can't see when I change the temperature
```
2021-05-15 10:33:13 DEBUG (MainThread) [pizone.controller] Writing message to 192.168.1.x{"SystemON": "on"}
2021-05-15 10:33:26 DEBUG (MainThread) [pizone.controller] Writing message to 192.168.1.x{"SystemON": "off"}
```

I deleted iZone integration many times, deleted in core.device_registries and re-added but unsuccessful.

IP/SystemSettings
`{"AirStreamDeviceUId":"0000426xx","DeviceType":"ASH","SysOn":"off","SysMode":"heat","SysFan":"low","SleepTimer":0,"UnitType":"Panasonic/Toshiba","Supply":"0.0","Setpoint":"26.0","Temp":"0.0","RAS":"zones","CtrlZone":15,"Tag1":"(type address here)","Tag2":"Aircon","Warnings":"none","ACError":" OK","Id":0,"EcoLock":"true","EcoMax":"30.0","EcoMin":"15.0","NoOfConst":1,"NoOfZones":4,"SysType":"320","AirflowLock":"onMin","UnitLocked":"false","FreeAir":"off","FanAuto":"disabled","OemMake":0}`

Please advise.

Cheers,

**Comment by SgtBatten** [comment] 2021-06-17 23:44
Just wondering if you have a similar setup to mine. My "living room" has two sensor entities. one is the climate.izone_controller and one is climate.living

I can only change the temp and the zone on/off using the climate.living and I can only change the system mode from the controller one.

So i setup both cards and hid the temp control from the controller one.  
![image](https://user-images.githubusercontent.com/24822223/122508326-29f25400-d045-11eb-9028-c336d21838af.png)

**Comment by LeVuHoang** [comment] 2021-06-18 09:57
I tried on both Controller and Climate.living but there is no temperature neither
<img width="787" alt="Screen Shot 2021-06-18 at 5 55 55 pm" src="https://user-images.githubusercontent.com/8195564/122543717-a9405180-d05e-11eb-8d66-0d9a2ccc4ccf.png">

**Comment by SgtBatten** [comment] 2021-06-18 22:49
On your a/c controller... In the config>zones settings, under 'type' for your living room is it set to "this touch screen" when you touch 'type'

If not, what is it set to. Do you have other rooms with sensors?

**Comment by LeVuHoang** [comment] 2021-06-19 15:45
I play around with different settings but there is no different in Home Assistant

![IMG_3923](https://user-images.githubusercontent.com/8195564/122647737-47641280-d158-11eb-8b8c-6bdab48c5560.PNG)
![IMG_3922](https://user-images.githubusercontent.com/8195564/122647740-48953f80-d158-11eb-93e0-c5e5aecf2437.jpg)
![IMG_3921](https://user-images.githubusercontent.com/8195564/122647741-492dd600-d158-11eb-8a2a-4c0844e2afb7.jpg)
![IMG_3924](https://user-images.githubusercontent.com/8195564/122647736-4206c800-d158-11eb-800c-73bf9c129038.PNG)

What settings are you using at the moment?

**Comment by SgtBatten** [comment] 2021-06-24 11:10
Yeah i would expect a temperature to be showing for the bottom two (Master and Living) based on what you've posted. 

Do the entities in HA not have any data for current temp?

**Comment by Swamp-Ig** [comment] 2021-06-25 04:45
Hey, Will try and have a look at this over the next week or two. It would seem to me that if 'this' is selected, then the thermostat should come up, although not really for the controller but for the zone.

**Comment by Swamp-Ig** [comment] 2021-06-25 09:24
Hi, can you look at `http://<ipaddr>/Zones1_4`  and see what it outputs? The Kitchen zone in my system which I have set to the 'this touchpad' zone looks like this:

```
{
      "AirStreamDeviceUId":"xxxx",
      "Id":0,
      "Index":0,
      "Name":"Kitchen",
      "Type":"auto",
      "Mode":"open",
      "SetPoint":20.500000,
      "Temp":16.190001,
      "MaxAir":100,
      "MinAir":0,
      "Const":255,
      "ConstA":"false",
      "DmpFlt":"false",
      "Master":"false",
      "iSense":"off"
   },
```

The corresponding kitchen zone in HA has a thermostat control as long as it's in auto mode. The controller itself doesn't have a temp displayed, but that is as designed since changing the controller temp doesn't do anything in zone control mode.

**Comment by LeVuHoang** [comment] 2021-06-26 02:46
> /Zones1_4

Hi,
This is the result
`[{"AirStreamDeviceUId":"0000xxxxx","Id":0,"Index":0,"Name":"Living","Type":"opcl","Mode":"close","SetPoint":15,"Temp":0,"MaxAir":100,"MinAir":0,"Const":255,"ConstA":"false","DmpFlt":"false","Master":"false","iSense":"off"},{"AirStreamDeviceUId":"0000xxxxx","Id":0,"Index":1,"Name":"Master","Type":"opcl","Mode":"open","SetPoint":15,"Temp":0,"MaxAir":80,"MinAir":0,"Const":255,"ConstA":"false","DmpFlt":"false","Master":"false","iSense":"off"},{"AirStreamDeviceUId":"0000xxxxx","Id":0,"Index":2,"Name":"Bed 2","Type":"opcl","Mode":"open","SetPoint":15,"Temp":0,"MaxAir":20,"MinAir":0,"Const":255,"ConstA":"false","DmpFlt":"false","Master":"false","iSense":"off"},{"AirStreamDeviceUId":"0000xxxxx","Id":0,"Index":3,"Name":"Bed 3","Type":"opcl","Mode":"close","SetPoint":23,"Temp":0,"MaxAir":50,"MinAir":0,"Const":255,"ConstA":"false","DmpFlt":"false","Master":"false","iSense":"off"}]`

I can see the different here is Type and and Mode.

**Comment by LeVuHoang** [comment] 2021-06-26 02:52
> Yeah i would expect a temperature to be showing for the bottom two (Master and Living) based on what you've posted.
> 
> Do the entities in HA not have any data for current temp?

It looks like there is no data for temp, I suppose this should be something to do with iZone setup but I don't know what config should I change to.

![iZone](https://user-images.githubusercontent.com/8195564/123499878-625ce800-d66c-11eb-9a82-67c02ad09fd2.PNG)
![iZone1](https://user-images.githubusercontent.com/8195564/123499900-891b1e80-d66c-11eb-8d9a-64ba6ee7fe5f.PNG)

**Comment by LeVuHoang** [comment] 2021-06-26 02:54
Could you please let me know what is under AC UNIT > Controlling Sensor and Zone?

Moreover, this is my current SystemSettings
`{"AirStreamDeviceUId":"0000xxxxx","DeviceType":"ASH","SysOn":"off","SysMode":"heat","SysFan":"high","SleepTimer":0,"UnitType":"Panasonic/Toshiba","Supply":"0.0","Setpoint":"28.0","Temp":"0.0","RAS":"zones","CtrlZone":15,"Tag1":"(type address here)","Tag2":"Aircon","Warnings":"none","ACError":" OK","Id":0,"EcoLock":"true","EcoMax":"30.0","EcoMin":"15.0","NoOfConst":1,"NoOfZones":4,"SysType":"320","AirflowLock":"off","UnitLocked":"false","FreeAir":"off","FanAuto":"disabled","OemMake":0}`

**Comment by Swamp-Ig** [comment] 2021-06-26 03:33
Yeh, so living and master are both open/closed zones, You can't change the temp for these zone types, they don't sense temperature they can just be opened and closed since there's no thermostat. 

If this is Zones1_4 then there's no zones there with a thermostat. You'll need to either set the controller to return air sensor mode (settings->AC Unit->Controlling sensor -> set to r/air), then you'll be able to change the controller temp. I think if you set it to Master it will control the temp from the touch screen, but it's up to you to figure that one out.

**Comment by Swamp-Ig** [comment] 2021-06-26 03:34
I'm going to close this because I think the HA stuff works as designed, it's a config issue on your end.

**Closed as completed by Swamp-Ig** 2021-06-26 03:34 UTC

**Comment by LeVuHoang** [comment] 2021-06-26 03:53
It's working, I just want to say Thank you to swamp-lg and SgtBatten.

**Comment by SgtBatten** [comment] 2021-06-27 23:32
Hmm, that was what I thought it was going to be but when you posted the image of the living and master zone setup showing wireless and touchpad i figured it was correctly setup.

FYI i have my "controlling sensor" set to "zones" rather than return air or master. 
The A/C company did get me to set one zone as a constant so that 'extra' air spills to that zone if necessary. I did this to a zone without it's own sensor which just has open/closed options. Seems to work well and spills even if set to closed.

**Comment by Swamp-Ig** [comment] 2021-06-28 00:47
I tried having no constant zone, but the unit just doesn't turn on at all. The company reccommends a loop-back constant zone that doesn't enter the general circulation. I'm contemplating setting that up, I tried getting a aircon company to quote it but it was rather a lot am sitting on it for now.
